platform :osx, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  require 'pathname'
  
  # 1. Update user project (Runner.xcodeproj) to register the package at workspace level
  user_project = installer.aggregate_targets.first.user_project
  user_project_dir = Pathname.new(user_project.path).dirname
  sfb_path = Pathname.new('/Users/axel10/projects/player_project/SFBAudioEngine')
  relative_to_user = sfb_path.relative_path_from(user_project_dir).to_s

  package_ref_user = user_project.root_object.package_references.find { |ref| ref.respond_to?(:relative_path) && ref.relative_path == relative_to_user }
  if package_ref_user.nil?
    package_ref_user = user_project.new(Xcodeproj::Project::Object::XCLocalSwiftPackageReference)
    package_ref_user.relative_path = relative_to_user
    user_project.root_object.package_references << package_ref_user
  end
  user_project.save

  # 2. Update Pods.xcodeproj to define package ref and link dependency on audio_core
  pods_project = installer.pods_project
  pods_project_dir = Pathname.new(pods_project.path).dirname
  relative_to_pods = sfb_path.relative_path_from(pods_project_dir).to_s

  package_ref_pods = pods_project.root_object.package_references.find { |ref| ref.respond_to?(:relative_path) && ref.relative_path == relative_to_pods }
  if package_ref_pods.nil?
    package_ref_pods = pods_project.new(Xcodeproj::Project::Object::XCLocalSwiftPackageReference)
    package_ref_pods.relative_path = relative_to_pods
    pods_project.root_object.package_references << package_ref_pods
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
    
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_ENABLE_EXPLICIT_MODULES'] = 'NO'
      config.build_settings['CLANG_ENABLE_EXPLICIT_MODULES'] = 'NO'
    end
    
    if target.name == 'audio_core'
      product_dep = target.package_product_dependencies.find { |dep| dep.product_name == 'SFBAudioEngine' }
      if product_dep.nil?
        product_dep = pods_project.new(Xcodeproj::Project::Object::XCSwiftPackageProductDependency)
        product_dep.package = package_ref_pods
        product_dep.product_name = 'SFBAudioEngine'
        target.package_product_dependencies << product_dep
      end
    end
  end
end
